version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=my-kthulu-app
      - DB_USER=admin
      - DB_PASSWORD=password
    networks:
      - my-kthulu-app-network
    depends_on:
      - postgres


  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB=my-kthulu-app
      POSTGRES_USER=admin
      POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - my-kthulu-app-network
    volumes:
      - my-kthulu-app-data:/var/lib/postgres

volumes:
  my-kthulu-app-data:

networks:
  my-kthulu-app-network:
    driver: bridge
